create table if not exists public."user" (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role text not null check (role in ('admin', 'player')),
  player_id text unique,
  is_active_player boolean not null default true
);

create table if not exists public.location_master (
  id bigint generated by default as identity primary key,
  facility_name text not null,
  address text,
  map_url text,
  phone_number text,
  email text,
  remark text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.category_master (
  id bigint generated by default as identity primary key,
  category_code text not null unique check (category_code in ('practice', 'match', 'event')),
  category_name text not null,
  display_order integer not null default 1,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.player_profile (
  user_id uuid primary key references public."user"(id) on delete cascade,
  photo_url text,
  jersey_name text,
  back_number integer,
  jersey_size text,
  birth_date date,
  nationality text,
  position text,
  current_status boolean not null default true,
  remark text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.schedule (
  id bigint generated by default as identity primary key,
  schedule_date date not null,
  start_time time,
  end_time time,
  category_id bigint not null references public.category_master(id) on delete restrict,
  location_id bigint references public.location_master(id) on delete set null,
  description text,
  created_by uuid not null references public."user"(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  schedule_id bigint not null references public.schedule(id) on delete cascade,
  user_id uuid not null references public."user"(id) on delete cascade,
  attendance_date date not null,
  status text not null check (status in ('present', 'absent', 'late')),
  note text,
  recorded_at timestamptz not null default now(),
  unique (schedule_id, user_id)
);

create index if not exists idx_schedule_schedule_date
on public.schedule(schedule_date);

create index if not exists idx_schedule_location_id
on public.schedule(location_id);

create index if not exists idx_schedule_category_id
on public.schedule(category_id);

create index if not exists idx_attendance_attendance_date
on public.attendance(attendance_date);

create index if not exists idx_attendance_user_id
on public.attendance(user_id);

alter table public."user" enable row level security;
alter table public.location_master enable row level security;
alter table public.category_master enable row level security;
alter table public.player_profile enable row level security;
alter table public.schedule enable row level security;
alter table public.attendance enable row level security;

create policy "Users can read own profile"
on public."user"
for select
to authenticated
using (auth.uid() = id);

create policy "Authenticated users can read users"
on public."user"
for select
to authenticated
using (true);

create policy "Authenticated users can read locations"
on public.location_master
for select
to authenticated
using (true);

create policy "Authenticated users can read categories"
on public.category_master
for select
to authenticated
using (true);

create policy "Admin can manage categories"
on public.category_master
for all
to authenticated
using (
  exists (
    select 1
    from public."user" as me
    where me.id = auth.uid()
      and me.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public."user" as me
    where me.id = auth.uid()
      and me.role = 'admin'
  )
);

create policy "Users can read own player profile and admins read all"
on public.player_profile
for select
to authenticated
using (
  user_id = auth.uid()
  or exists (
    select 1
    from public."user" as me
    where me.id = auth.uid()
      and me.role = 'admin'
  )
);

create policy "Users can manage own player profile and admins manage all"
on public.player_profile
for all
to authenticated
using (
  user_id = auth.uid()
  or exists (
    select 1
    from public."user" as me
    where me.id = auth.uid()
      and me.role = 'admin'
  )
)
with check (
  user_id = auth.uid()
  or exists (
    select 1
    from public."user" as me
    where me.id = auth.uid()
      and me.role = 'admin'
  )
);

create policy "Admin can manage locations"
on public.location_master
for all
to authenticated
using (
  exists (
    select 1
    from public."user" as me
    where me.id = auth.uid()
      and me.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public."user" as me
    where me.id = auth.uid()
      and me.role = 'admin'
  )
);

create policy "Authenticated users can read schedules"
on public.schedule
for select
to authenticated
using (true);

create policy "Admin can insert schedules"
on public.schedule
for insert
to authenticated
with check (
  created_by = auth.uid()
  and exists (
    select 1
    from public."user" as me
    where me.id = auth.uid()
      and me.role = 'admin'
  )
);

create policy "Admin can update schedules"
on public.schedule
for update
to authenticated
using (
  exists (
    select 1
    from public."user" as me
    where me.id = auth.uid()
      and me.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public."user" as me
    where me.id = auth.uid()
      and me.role = 'admin'
  )
);

create policy "Admin can delete schedules"
on public.schedule
for delete
to authenticated
using (
  exists (
    select 1
    from public."user" as me
    where me.id = auth.uid()
      and me.role = 'admin'
  )
);

create policy "Authenticated users can read attendance"
on public.attendance
for select
to authenticated
using (
  exists (
    select 1
    from public."user" as me
    where me.id = auth.uid()
  )
);

create policy "Users can insert own attendance and admins insert all"
on public.attendance
for insert
to authenticated
with check (
  user_id = auth.uid()
  or exists (
    select 1
    from public."user" as me
    where me.id = auth.uid()
      and me.role = 'admin'
  )
);

create policy "Users can update own attendance and admins update all"
on public.attendance
for update
to authenticated
using (
  user_id = auth.uid()
  or exists (
    select 1
    from public."user" as me
    where me.id = auth.uid()
      and me.role = 'admin'
  )
)
with check (
  user_id = auth.uid()
  or exists (
    select 1
    from public."user" as me
    where me.id = auth.uid()
      and me.role = 'admin'
  )
);

create policy "Admin can manage attendance"
on public.attendance
for all
to authenticated
using (
  exists (
    select 1
    from public."user" as me
    where me.id = auth.uid()
      and me.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public."user" as me
    where me.id = auth.uid()
      and me.role = 'admin'
  )
);
